name: Linux (Flatpak)

on:
  workflow_dispatch:
    inputs:
      myCommit:
        description: Commit SHA1
        required: false
        default: ''
        type: string
      releaseTag:
        description: Release tag
        required: false
        default: ''
        type: string
  workflow_call:
    inputs:
      myCommit:
        description: Commit SHA1
        required: false
        default: ''
        type: string
      releaseTag:
        description: Release tag
        required: false
        default: ''
        type: string
  push: null
  pull_request: null
  release:
    types:
      - published

jobs:
  build-flatpak-bundle:
    name: "Build flatpak bundle"
    runs-on: ubuntu-latest
    container:
      image: bilelmoussaoui/flatpak-github-actions:freedesktop-23.08
      options: --privileged
    strategy:
      matrix:
        arch:
          - x86_64
          - arm64

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: false

    - name: Set up Docker
      if: ${{ matrix.arch != 'x86_64' }}
      run: |
        dnf install -y docker

    - name: Set up QEMU
      if: ${{ matrix.arch != 'x86_64' }}
      id: qemu
      uses: docker/setup-qemu-action@v2
      with:
        platforms: arm64

    - name: Run Flatpak build
      uses: flatpak/flatpak-github-actions/flatpak-builder@v6
      with:
        bundle: io.github.openenroth.openenroth_${{inputs.releaseTag}}_${{ matrix.arch }}.flatpak
        manifest-path: distribution/linux/flatpak/io.github.openenroth.openenroth.yml
        cache-key: flatpak-builder-${{ github.sha }}_${{ matrix.arch }}
        upload-artifact: true

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: io.github.openenroth.openenroth_${{inputs.releaseTag}}_${{ matrix.arch }}.flatpak
        path: io.github.openenroth.openenroth_${{inputs.releaseTag}}_${{ matrix.arch }}.flatpak
        retention-days: 0

    - name: Publish release
      if: inputs.releaseTag != ''
      uses: softprops/action-gh-release@v1
      with:
        prerelease: true
        tag_name: '${{inputs.releaseTag}}'
        files: io.github.openenroth.openenroth_${{inputs.releaseTag}}_${{ matrix.arch }}.flatpak
